[package]
name = "jam4"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
sdfu = { workspace = true }
bevy_smud = { workspace = true }
utils = { path = "../utils", version = "0.1.0" }
bevy_hanabi = { workspace = true }
